//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public Nullable<System.DateTime> born_date { get; set; }
        public string passport_series { get; set; }
        public string passport_number { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string insurance_policy { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
